---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
    owner: hce
  name: example
  namespace: app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
      timeoutSeconds: 100
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - image: quay.io/oktaysavdi/istioproject@sha256:e92c62f3de5048b1583f5ede446005f64c3d7154fcd39ce7ab4765e490f3cdea
          name: example
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
          readinessProbe:
            exec:
              command:
                - ls
                - /opt
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            exec:
              command:
                - ls
                - /opt
            initialDelaySeconds: 2
            periodSeconds: 5
