checks:
  doNotAutoAddDefaults: true
  include:
    - "privileged-container"
    - "run-as-non-root"
    - "dangling-ingress"
    - "drop-net-raw-capability"
    - "duplicate-env-var"
    - "env-var-secret"
    - "exposed-services"
    - "host-ipc"
    - "host-network"
    - "host-pid"
    - "hpa-minimum-three-replicas"
    - "latest-tag"
    - "minimum-three-replicas"
    - "mismatching-selector"
    - "no-liveness-probe"
    - "no-read-only-root-fs"
    - "no-readiness-probe"
    - "no-rolling-update-strategy"
    - "non-existent-service-account"
    - "privilege-escalation-container"
    - "read-secret-from-env-var"
    - "required-label-owner"
    - "sensitive-host-mounts"
    - "unsafe-proc-mount"
    - "unsafe-sysctls"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "use-namespace"
    - "wildcard-in-rules"
